<?php
/**
 * @var $block \Magento\Reports\Block\Product\Viewed
 */
?>
<?php
if ($exist = ($block->getRecentlyViewedProducts() && $block->getRecentlyViewedProducts()->getSize())) {
    $type = 'widget-viewed';
    $mode = 'list';

    $type = $type . '-' . $mode;

    $items = $block->getRecentlyViewedProducts();
}
?>
<?php if ($exist): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col name"><?= /* @escapeNotVerified */ __('Name') ?></th>
                <th scope="col" class="col sku"><?= /* @escapeNotVerified */ __('SKU') ?></th>
                <th scope="col" class="col price"><?= /* @escapeNotVerified */ __('Price') ?></th>
                <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $_item): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col name"><?= $block->escapeHtml($_item->getName()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col sku"><?= /* @escapeNotVerified */ $_item->getSku() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col price">
                        <?php /* @escapeNotVerified */ echo $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                            \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                            [
                                'price_id_suffix' => '-' . $type
                            ]
                        ) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <div class="product-item-actions">
                            <div class="actions-primary">
                                <button class="action view"
                                        data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>"}}'
                                        type="button" title="<?= /* @escapeNotVerified */ __('View') ?>">
                                    <span><?= /* @escapeNotVerified */ __('View') ?></span>
                                </button>
                            </div
                            <span> </span>
                            <div class="actions-primary">
                                <?php if ($_item->isSaleable()): ?>
                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                        <button class="action tocart primary"
                                                data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}'
                                                type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                        </button>
                                    <?php else: ?>
                                        <?php
                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
                                        ?>
                                        <button class="action tocart primary"
                                                data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                        </button>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if ($_item->getIsSalable()): ?>
                                        <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have not viewed any products recently.') ?></span></div>
<?php endif ?>
